name       : xonotic
version    : 0.8.2
release    : 3
source     :
    - http://dl.xonotic.org/xonotic-0.8.2.zip : a22f7230f486c5825b55cfdadd73399c9b0fae98c9e081dd8ac76eca08359ad5
license    :
    - GPL-2.0
    - GPL-3.0
component  : games.action
summary    : Xonotic - The Free and Fast Arena Shooter
description: |
    Xonotic is an addictive, arena-style first person shooter with crisp movement and a wide array of weapons. It combines intuitive mechanics with in-your-face action to elevate your heart rate.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    pushd source/d0_blind_id
    %configure --disable-static --prefix=/usr --disable-rijndael
    popd
build      : "# crypto stuff\npushd source/d0_blind_id\n%make\npopd\n\npushd $workdir/source/darkplaces\n\
    # compile glx client\n%make DP_FS_BASEDIR=/usr/share/xonotic cl-release\n# compile\
    \ server\n%make DP_FS_BASEDIR=/usr/share/xonotic sv-release\n# compile sdl client\n\
    %make DP_FS_BASEDIR=/usr/share/xonotic sdl-release \npopd\n"
install    : |
    pushd $workdir/source/d0_blind_id
    %make_install
    popd

    # compiled binaries
    install -Dm 0755 source/darkplaces/darkplaces-dedicated $installdir/usr/bin/xonotic-dedicated
    install -Dm 0755 source/darkplaces/darkplaces-glx $installdir/usr/bin/xonotic-glx
    install -Dm 0755 source/darkplaces/darkplaces-sdl $installdir/usr/bin/xonotic-sdl

    # data files
    install -Dm 0644 data/*.pk3 -t $installdir/usr/share/xonotic/data
    install -Dm 0644 key_0.d0pk $installdir/usr/share/xonotic

    # shortcuts and icons
    sed -i 's|^\(Icon=\).*|\1xonotic|g' misc/logos/*.desktop

    install -Dm 0644 misc/logos/*.desktop -t $installdir/usr/share/applications

    for size in 16 22 24 32 48 64 128 256 512; do
        install -Dm 0644 misc/logos/icons_png/xonotic_${size}.png \
        "$installdir/usr/share/icons/hicolor/${size}x${size}/apps/xonotic.png"
    done

