name       : xonotic
version    : 0.8.2
release    : 7
source     :
    - http://dl.xonotic.org/xonotic-0.8.2.zip : a22f7230f486c5825b55cfdadd73399c9b0fae98c9e081dd8ac76eca08359ad5
homepage   : https://xonotic.org/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-laer
component  : games.action
summary    : Xonotic - The Free and Fast Arena Shooter
description: |
    Xonotic is an addictive, arena-style first person shooter with crisp movement and a wide array of weapons. It combines intuitive mechanics with in-your-face action to elevate your heart rate.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    %patch -p1 < $pkgfiles/gcc11-typedef-alignment.patch 
    pushd source/d0_blind_id
    %configure --disable-static --prefix=/usr --disable-rijndael
    popd
build      : |
    # crypto stuff
    pushd source/d0_blind_id
    %make
    popd

    pushd $workdir/source/darkplaces
    # compile glx client
    %make DP_FS_BASEDIR=/usr/share/xonotic cl-release
    # compile server
    %make DP_FS_BASEDIR=/usr/share/xonotic sv-release
    # compile sdl client
    %make DP_FS_BASEDIR=/usr/share/xonotic sdl-release 
    popd
install    : |
    pushd $workdir/source/d0_blind_id
    %make_install
    popd

    # compiled binaries
    install -Dm00755 source/darkplaces/darkplaces-dedicated $installdir/usr/bin/xonotic-dedicated
    install -Dm00755 source/darkplaces/darkplaces-glx $installdir/usr/bin/xonotic-glx
    install -Dm00755 source/darkplaces/darkplaces-sdl $installdir/usr/bin/xonotic-sdl

    # data files
    install -Dm00644 data/*.pk3 -t $installdir/usr/share/xonotic/data
    install -Dm00644 key_0.d0pk $installdir/usr/share/xonotic

    # shortcuts and icons
    sed -i 's|^\(Icon=\).*|\1xonotic|g' misc/logos/*.desktop

    install -Dm00644 misc/logos/*.desktop -t $installdir/usr/share/applications

    for size in 16 22 24 32 48 64 128 256 512; do
        install -Dm00644 misc/logos/icons_png/xonotic_${size}.png \
        "$installdir/usr/share/icons/hicolor/${size}x${size}/apps/xonotic.png"
    done

